### ISSUE TITLE
Install failed

### ISSUE THREAD

**Issue by akram1** [blooparksystems/bp_blog_author_information#1]
no such module
bp_8_0_social_media_for_res_partner

**Comment by Benniphx** [comment]
Hi akram1 
I added the missing Add-on to the Github as well.
I changed the dependency to the new name bp_social_media_for_res_partner. 
So you have to pull/update the bp_blog_author_information add-on and also have to get the bp_social_media_for_res_partner add-on.

Greetings Ben
